### ISSUE TITLE
Submit to Keepass Plugin Repository?

### ISSUE THREAD

**Issue by numericOverflow** [djherbis/keepass-pinentry#4]
I came across your plugin via a google search.  Any reason you don't have it submitted/listed on the official Keepass plugin repository?

**Comment by numericOverflow** [comment]
https://keepass.info/plugins.html

**Comment by djherbis** [comment]
Hey, I guess I'd be happy to have it listed there, but I didn't see a way to submit it to be shown there?

**Comment by apollo2k4** [comment]
> Hey, I guess I'd be happy to have it listed there, but I didn't see a way to submit it to be shown there?

Write message on a forum, the author quickly answer enough and adds it to repository.

**Comment by djherbis** [comment]
Posted, I'll close this if it gets added, thanks.

**Comment by djherbis** [comment]
It's been added to https://keepass.info/plugins.html, thanks!
