### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by ThePirate42** [djherbis/keepass-pinentry#8]
I can't see a license file, does this software have a license?

I need it because I'm working on #7, I'm trying to package the plugin for Linux, and having the license would be nice.

**Comment by djherbis** [comment]
@ThePirate42 Would MIT be permissible for ya? I'm pretty open and usually run with MIT.

**Comment by ThePirate42** [comment]
Sure MIT is ok, any open source license is good as long as it permits distributing binaries.

**Comment by djherbis** [comment]
Done https://github.com/djherbis/keepass-pinentry/commit/6690bf65be893af21200fe115ce4c8fb90d7994b
